project:
  type: website
  output-dir: docs

website:
  title: "InVEST Schistosomiasis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: getting_started.qmd
        text: Getting started
      - href: about.qmd
        text: About
      - href: tutorials.qmd
        text: Tutorials

format:
  html:
    theme: spacelab #https://bootswatch.com/
    css: styles.css
    toc: true



